In [1]:
import numpy as np

In [2]:
list1 = [[1,2,3], [4,5,6]]
list1

[[1, 2, 3], [4, 5, 6]]

In [3]:
a1 = np.array(list1)
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a1.dtype

dtype('int32')

In [6]:
a0 = np.zeros((4,3), dtype=int)
a0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
a1s = np.ones((5,5), dtype=int)
a1s

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
arand = np.random.normal(0, 1, size=(3,4))
arand

array([[-1.38460221,  0.46363913, -0.08747541,  0.52055488],
       [ 1.67696402, -0.06494427, -0.47504895, -1.16718573],
       [ 0.58237645,  0.81070587, -1.19194307,  1.69745282]])